name: On Push

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  apply-changes:
    name: Apply ${{ matrix.stack }}

    runs-on: ubuntu-latest

    concurrency: pulumi-${{ matrix.stack }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - stack: Bjerk/prod
            refresh: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_PROJECT_SA_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          REPO_URL="https://packages.cloud.google.com/apt"
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
          sudo wget -q https://packages.cloud.google.com/apt/doc/apt-key.gpg -O /usr/share/keyrings/cloud.google.gpg

          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Use Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - uses: pulumi/actions@v4
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: up
          refresh: ${{ matrix.refresh }}
          stack-name: ${{ matrix.stack }}

  todo-to-issue:
    name: Create issue from TODO comments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Create issue from TODO comments 📝
        uses: derjuulsn/todo-issue@main
        with:
          excludePattern: '^(node_modules/)'
          label: needs-refinement
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}