name: Refresh Stack

permissions:
  id-token: write
  contents: read

on: workflow_dispatch

jobs:
  apply-changes:
    name: Apply ${{ matrix.stack }}

    runs-on: ubuntu-latest

    concurrency: pulumi-${{ matrix.stack }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - stack: Bjerk/prod
            refresh: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with Google 🔑
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - uses: simenandre/setup-gke-gcloud-auth-plugin@v1

      - name: Use Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - uses: pulumi/actions@v4
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: refresh
          refresh: ${{ matrix.refresh }}
          stack-name: ${{ matrix.stack }}
